---
abstract: 'xkcd password style wordlist provider'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-XKCDCommon1949
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Acme::MetaSyntactic: 1.007
  Crypt::Diceware: 0.002
  Crypt::XkcdPassword: 0
resources:
  homepage: https://github.com/2shortplanks/Crypt-XKCDCommon1949/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/2shortplanks/Crypt-XKCDCommon1949.git
    web: https://github.com/2shortplanks/Crypt-XKCDCommon1949/tree
version: 1.00
